### ISSUE TITLE
Crash on startup Int32 parse exception

### ISSUE THREAD

**Issue by naizarak** [ciribob/DCS-SimpleRadioStandalone#274]
ClientX and ClientY params in client.cfg are parsed as ints but can contain decimals (probably caused by custom display scale factor).

`SharpConfig.SettingValueCastException: Failed to convert value '261.6' to type System.Int32. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at SharpConfig.Int32StringConverter.ConvertFromString(String value, Type hint)
   at SharpConfig.Setting.CreateObjectFromString(String value, Type dstType)
   --- End of inner exception stack trace ---
   at SharpConfig.Setting.CreateObjectFromString(String value, Type dstType)
   at SharpConfig.Setting.GetValue[T]()
   at Ciribob.DCS.SimpleRadio.Standalone.Client.UI.MainWindow.CheckWindowVisibility()
   at Ciribob.DCS.SimpleRadio.Standalone.Client.UI.MainWindow..ctor()`

**Comment by MorpheusXAUT** [comment]
Hi,

Thanks for reporting this, we'll have a fix out with the next update!

**Comment by MorpheusXAUT** [comment]
Fixed in aead8d40e03d7eeb6cd62c4e34cf944c7f5917df, update will be released this week, most likely on Thursday.
