### ISSUE TITLE
VOIP issues - System.ObjectDisposedException and System.ArgumentException

### ISSUE THREAD

**Issue by obfuscoder** [ciribob/DCS-SimpleRadioStandalone#339]
I have been issues with SRS on the VOIP part lately. Scanning through the client log file I can find the following issues:

1. SystemArgumentExceptions

These exception happend quite often. It might be due to a bad internet connection. It happens a lot in the evenings when I assume there is a lot of video streaming used by other clients of my ISP:

```
Ciribob.DCS.SimpleRadio.Standalone.Common.Network.UDPVoicePacket | Failed to decode voice packet System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Ciribob.DCS.SimpleRadio.Standalone.Common.Network.UDPVoicePacket._DecodeVoicePacket(Byte[] encodedOpusAudio, Boolean decode) in D:\Dropbox\Dev\DCS\DCS-SRS\DCS-SR-Common\Network\UDPVoicePacket.cs:line 207
   at Ciribob.DCS.SimpleRadio.Standalone.Common.Network.UDPVoicePacket.DecodeVoicePacket(Byte[] encodedOpusAudio, Boolean decode) in D:\Dropbox\Dev\DCS\DCS-SRS\DCS-SR-Common\Network\UDPVoicePacket.cs:line 175
```

2. System.ObjectDisposedException

Those exceptions happen to occur during attempts to connect/reconnect to a server:

```
Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientSync | Could not connect to server System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.TcpClient'.
   at System.Net.Sockets.TcpClient.GetStream()
   at Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientSync.ClientSyncLoop()
   at Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientSync.Connect()
```

and

```
Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientSync | Could not connect to server System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientSync.Connect()
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

**Comment by ciribob** [comment]
Will be solved in the next release in a week or so - please re-open if you see it after the 1.7.0.0 release
