### ISSUE TITLE
SRS Server Memory Spike

### ISSUE THREAD

**Issue by rurounijones** [ciribob/DCS-SimpleRadioStandalone#428]
[8:07 AM] LazyBoot: Noticed a massive spray of 
```plain
2020-03-08 17:54:59.9215 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Exception Handling Message Array dimensions exceeded supported range. System.OverflowException: Array dimensions exceeded supported range.
   at NetCoreServer.Buffer.Reserve(Int64 capacity)
   at NetCoreServer.Buffer.Append(Byte[] buffer, Int64 offset, Int64 size)
   at NetCoreServer.TcpSession.SendAsync(Byte[] buffer, Int64 offset, Int64 size)
   at NetCoreServer.TcpServer.MulticastAllExeceptOne(String text, Guid guid)
   at Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync.HandleClientRadioUpdate(SRSClientSession session, NetworkMessage message, Boolean send)
   at Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync.HandleMessage(SRSClientSession state, NetworkMessage message)
```
 in the logs, combined with increasing memory usage and eventually leading to a crash of the srs server
[8:13 AM] LazyBoot: also seeing a bunch of these 

```plain
2020-03-08 05:26:01.5193 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.SRSClientSession | Socket Exception: System.InvalidOperationException: "An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.";
   at System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring()
   at System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[] buffer, Int32 offset, Int32 count)
   at NetCoreServer.TcpSession.TrySend() System.InvalidOperationException: "An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.";
   at System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring()
   at System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[] buffer, Int32 offset, Int32 count)
   at NetCoreServer.TcpSession.TrySend()
2020-03-08 05:26:01.5193 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Disconnecting Client 
2020-03-08 05:26:01.5193 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Removed Disconnected Client bmxxbmLjSr-h5cia4ti-IA
```
[8:14 AM] LazyBoot: not sure which one (if either) is responsible, but one of our servers recently saw SRS server spike up to 17GB of memory used

![pgaw-memory-spike](https://user-images.githubusercontent.com/21911/76205024-60f67a80-61f1-11ea-95fe-6352b165a4c1.png)

**Comment by rurounijones** [comment]
`Exception Handling Message Array dimensions exceeded supported range.`

> .NET Framework only: By default, the maximum size of an Array is 2 gigabytes (GB). In a 64-bit environment, you can avoid the size restriction by setting the enabled attribute of the gcAllowVeryLargeObjects configuration element to true in the run-time environment.

https://docs.microsoft.com/en-us/dotnet/api/system.array?view=netframework-4.8

So the issue with that exception is that we are attempting to size the buffer `byte[]` [array](https://github.com/ciribob/DCS-SimpleRadioStandalone/blob/master/DCS-SimpleRadio%20Server/Network/NetCoreServer/Buffer.cs#L87) to be more than is allows.

**Comment by rurounijones** [comment]
`Socket Exception: System.InvalidOperationException: "An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.";`

https://github.com/akkadotnet/akka.net/issues/3572

"Will be part of v1.4.0 and possibly 1.3.18."

**Comment by LazyBoot** [comment]
from a dump showing the issue more clearly
![memory dump](https://cdn.discordapp.com/attachments/598575126530752540/686602897425039426/unknown.png)

**Comment by ciribob** [comment]
Looks like there is an update to add all the actions onto a queue so you can't attempt to do more than one at a time. Will have a look at a release today to see if that helps

**Comment by LazyBoot** [comment]
Still showing similar issues with the latest beta
![image](https://user-images.githubusercontent.com/3827482/76692359-c3b69e80-6655-11ea-8540-5b545020cd1c.png)
![image](https://user-images.githubusercontent.com/3827482/76692360-c6b18f00-6655-11ea-8324-976b4e65bfdd.png)

**Comment by ciribob** [comment]
Working on this in branch https://github.com/ciribob/DCS-SimpleRadioStandalone/tree/tcp-change-again

**Comment by ciribob** [comment]
This should be fixed in 1.7.8.0

Let me know if not!

**Comment by ciribob** [comment]
Is this OK to close now?

**Comment by LazyBoot** [comment]
Orange is SRS, seems fine
![image](https://user-images.githubusercontent.com/3827482/80283872-3d44b080-871b-11ea-9065-2f81764b0331.png)

**Comment by ciribob** [comment]
Thanks! Will close

**Comment by Ilkhom-S** [comment]
How did you solve this issue ?

**Comment by ciribob** [comment]
Library update and a try catch fixed it

**Comment by Ilkhom-S** [comment]
Ifound solution to NetCore server, and fixed . there was memory leak on library
