### ISSUE TITLE
Random disconnections during mission

### ISSUE THREAD

**Issue by Tsukumoyarei** [ciribob/DCS-SimpleRadioStandalone#656]
Happens almost everyday, here is a log from the latest one:

2023-05-21 21:32:02.9441 | Ciribob.DCS.SimpleRadio.Standalone.Client.Network.SRSClientSyncHandler | Client exception reading - Disconnecting  System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at Ciribob.DCS.SimpleRadio.Standalone.Client.Network.SRSClientSyncHandler.ClientSyncLoop()
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
2023-05-21 21:32:02.9441 | Ciribob.DCS.SimpleRadio.Standalone.Client.Network.SRSClientSyncHandler | Disconnecting from server 
2023-05-21 21:32:02.9968 | Ciribob.DCS.SimpleRadio.Standalone.Client.Network.SRSClientSyncHandler | Disconnecting from server 

connection with the server is tested via tcping with no package loss and very rare high pings:

'Ping statistics for xxxxxxxxxxxxxx
     246 probes sent.
     246 successful, 0 failed.  (0.00% fail)
Approximate trip times in milli-seconds:
     Minimum = 14.353ms, Maximum = 1019.933ms, Average = 30.467ms'

I hope there is an auto-reconnect function in case of sudden disconnect, otherwise a keybind for reconnect would be useful. For now I have to switch from my VR to desktop and reconnect every time, while my plane flies uncontrolled (which is a serious issue while formation flying and/or case 1 recovery.)

**Comment by ciribob** [comment]
For SRS support - please jump onto the SRS discord and see the common issues section, as well as posting your info

Link is in the help section on the SRS client
