### ISSUE TITLE
Join seconded server.srs client hang and crashed.

### ISSUE THREAD

**Issue by Handsome1080P** [ciribob/DCS-SimpleRadioStandalone#693]
Can't close by exit the icon,need force end in taskmanager.Try to fresh install srs and system,no joy.

Crash logs.
```See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at DCS_SR_Client.App.NotifyIcon_Show(Object sender, EventArgs args)
   at System.Windows.Forms.NotifyIcon.OnDoubleClick(EventArgs e)
   at System.Windows.Forms.NotifyIcon.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SR-ClientRadio
    Assembly Version: 2.1.0.1
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
Sentry
    Assembly Version: 3.20.1.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
NLog
    Assembly Version: 5.0.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 6.0.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.1
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
SharpConfig
    Assembly Version: 3.2.9.1
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MahApps.Metro
    Assembly Version: 1.5.0.23
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
DCS-SR-Common
    Assembly Version: 1.0.0.1
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
NAudio
    Assembly Version: 1.8.4.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
Octokit
    Assembly Version: 2.0.1.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Windows.Interactivity
    Assembly Version: 4.5.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
PresentationUI
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationUI/v4.0_4.0.0.0__31bf3856ad364e35/PresentationUI.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
SharpDX.DirectInput
    Assembly Version: 4.2.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
SharpDX.XInput
    Assembly Version: 4.2.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
SharpDX
    Assembly Version: 4.2.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
MathNet.Filtering
    Assembly Version: 0.7.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
WPFCustomMessageBox
    Assembly Version: 1.0.7.39267
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
OpusWrapper
    Assembly Version: 1.0.0.1
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
Easy.MessageHub
    Assembly Version: 0.0.0.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
WebRtcVadSharp
    Assembly Version: 1.3.2.0
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Program%20Files/DCS-SimpleRadio-Standalone/SR-ClientRadio.exe
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ciribob** [comment]
For support please come to the SRS discord (use a throwaway account  on the web if you're worried about privacy as it's easier to support there and for others to help)

Please follow the pinned post in dcs-common-issues
