### ISSUE TITLE
SRS Dedicated Server: Error processing Sending Queue UDP Packet: The operation was canceled. 

### ISSUE THREAD

**Issue by tazdirector** [ciribob/DCS-SimpleRadioStandalone#699]
Running into an ongoing issues with an SRS dedicated server.
After a random amount of time, UDP packets get blocked, causing clients to fail VOIP connection.

A quick SRS Server reboot solves the issue temporarily.

Confirmed TCP/UDP ports are open for 5002/5003 and Server is launching with admin properties from C:\Program Files (x86) folder.

Partial logs listed here (IPs hidden for security reasons)
```
2024-04-01 12:45:52.8676 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.SRSClientSession | Client connected: IP 104.#.#.# | Port 61081 
2024-04-01 12:49:11.0151 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.SRSClientSession | Client disconnected: IP 104.#.#.# | Port 61081 
2024-04-01 12:49:11.0151 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Disconnecting Client 
2024-04-01 12:49:11.0151 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Removed Disconnected Client kjzW2XEkQUmitX2nXNXbZA 
2024-04-01 12:59:49.9057 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Error receving audio UDP for client A blocking operation was interrupted by a call to WSACancelBlockingCall System.Net.Sockets.SocketException (0x80004005): A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at System.Net.Sockets.UdpClient.Receive(IPEndPoint& remoteEP)
   at Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter.Listen()
2024-04-01 12:59:49.9057 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Error processing Sending Queue UDP Packet: The operation was canceled. 
2024-04-01 12:59:49.9057 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Failed to Process UDP Packet: The operation was canceled. 
2024-04-01 12:59:56.2345 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerState | 'C:\Program Files (x86)\DCS-SimpleRadioStandalone\banned.txt' was not found or you don't have permission to read the file 
2024-04-01 12:59:56.2345 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Test Frequency: 247200000 
2024-04-01 12:59:56.2345 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Test Frequency: 120300000 
2024-04-01 12:59:56.2345 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Global Frequency: 248220000 
2024-04-01 12:59:56.3968 | Ciribob.DCS.SimpleRadio.Standalone.Server.UI.MainWindow.MainViewModel | DCS-SRS Server Running - 2.1.0.2 
2024-04-01 12:59:56.7607 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.Models.TransmissionLoggingQueue | EVENT, TRANSMISSION LOGGING ENABLED 
2024-04-01 12:59:58.3889 | Ciribob.DCS.SimpleRadio.Standalone.Common.UpdaterChecker | Running latest stable version: 2.1.0.2 
2024-04-01 13:05:12.0604 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.SRSClientSession | Client connected: IP 192.#.#.# | Port 5002 
2024-04-01 13:05:19.5036 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.SRSClientSession | Client connected: IP 104.#.#.# | Port 47814 

```

**Comment by ciribob** [comment]
Its port 5002 (not 5003) - i'd check a local firewall and make sure you definitely port forwarded.

it'll be a networking issue rather than SRS so i'll close for now 👍
